### PR TITLE
Dev -> Stage Sync (February 2024 Release)

### PR DESCRIPTION
**Pull request by anthonypetersen**
Issues Addressed
-----
* [QOL/PROMIS Survey PWA/Trigger](https://github.com/episphere/connect/issues/877) - @anthonypetersen 
* [Update UI displaying notifications that have been sent](https://github.com/episphere/connect/issues/875) - @we-ai 
* [Age Range Expansion - PWA - Remaining Items](https://github.com/episphere/connect/issues/868) - @we-ai 
* [iframe blocked for HIPAA and Consent forms in Prod](https://github.com/episphere/connect/issues/887) - @Gbarra9 
* [Send Magic Link Email with NCI email server](https://github.com/episphere/connect/issues/731) - @jhflorey 
* [Fix signed pdf coordinates in PWA and SMDB](https://github.com/episphere/connect/issues/879) - @bransteitterbr

### CODE REVIEW

**Comment by Gbarra9** [comment]
My issue has been tested in dev and ready to be moved to stage.
- https://github.com/episphere/connect/issues/887

**Comment by anthonypetersen** [comment]
my issue has been tested and is ready for stage

**Review by jhflorey — APPROVED** [review]

**Comment by we-ai** [comment]
My updates (notification messages; age expansion implementations and fixes on old problems) were tested in dev, and are ready for stage.

**Review by we-ai — APPROVED** [review]

**Review by bransteitterbr — APPROVED** [review]

**Comment by bransteitterbr** [comment]
My changes have been tested and are ready for stage

**Pull request merged**
