### PR TITLE
Stage -> Prod Sync (June 2024)

### PR DESCRIPTION
**Pull request by anthonypetersen**
Issues Addressed
-----
* https://github.com/episphere/connect/issues/885 - @Gbarra9 
* https://github.com/episphere/connect/issues/945 - @JoeArmani 
* https://github.com/episphere/connect/issues/915 - @amber-emmes

### CODE REVIEW

**Comment by jhflorey** [comment]
https://github.com/episphere/connect/issues/885 ready for prod

**Review by jhflorey — APPROVED** [review]

**Review by JoeArmani — APPROVED** [review]
ready for prod

**Review by Gbarra9 — APPROVED** [review]
My updates were tested in stage and ready for prod.

**Review by amber-emmes — APPROVED** [review]
Should be good to go.

**Pull request merged**
