### PR TITLE
Stage -> Prod Sync (February 2024 Release)

### PR DESCRIPTION
**Pull request by anthonypetersen**
Issues Addressed
-----
* [QOL/PROMIS Survey PWA/Trigger](https://github.com/episphere/connect/issues/877) - @anthonypetersen 
* [Update UI displaying notifications that have been sent](https://github.com/episphere/connect/issues/875) - @we-ai 
* [Age Range Expansion - PWA - Remaining Items](https://github.com/episphere/connect/issues/868) - @we-ai 
* [iframe blocked for HIPAA and Consent forms in Prod](https://github.com/episphere/connect/issues/887) - @Gbarra9 
* [Send Magic Link Email with NCI email server](https://github.com/episphere/connect/issues/731) - @jhflorey 
* [Fix signed pdf coordinates in PWA and SMDB](https://github.com/episphere/connect/issues/879) - @bransteitterbr 
* [Update survey handling on survey continuation](https://github.com/episphere/connectApp/pull/723) - @JoeArmani

### CODE REVIEW

**Comment by we-ai** [comment]
My updates are ready for prod.

**Review by we-ai — APPROVED** [review]

**Comment by Gbarra9** [comment]
My change is ready for prod.
- https://github.com/episphere/connect/issues/887#issuecomment-1969528236

**Review by Gbarra9 — APPROVED** [review]

**Comment by bransteitterbr** [comment]
My change is ready for prod

https://github.com/episphere/connect/issues/879#issuecomment-1969155826

**Comment by anthonypetersen** [comment]
changes approved and ready for prod

**Comment by jhflorey** [comment]
My change is ready for prod

**Review by jhflorey — APPROVED** [review]

**Comment by Gbarra9** [comment]
Made late change to remove the sandbox attribute from dev and stage as it was not needed anymore. 
- https://github.com/episphere/connectApp/pull/728
- https://github.com/episphere/connect/issues/887#issuecomment-1971562472

**Pull request merged**
