### PR TITLE
Stage -> Prod Sync (July 2024 Release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- https://github.com/episphere/connect/issues/917 (@anthonypetersen)
- https://github.com/episphere/connect/issues/915 (@bransteitterbr)
- https://github.com/episphere/connect/issues/1048 (@JoeArmani)
- https://github.com/episphere/connect/issues/1017 (@jhflorey)
- https://github.com/episphere/connect/issues/1057 (@jhflorey)
- https://github.com/episphere/connect/issues/1066 (@JoeArmani)
- https://github.com/episphere/connect/issues/1050 (@bransteitterbr)
- https://github.com/episphere/connect/issues/621 (@Gbarra9)
- https://github.com/episphere/connectApp/pull/821 (@anthonypetersen)

### CODE REVIEW

**Review by Gbarra9 — APPROVED** [review]
Changes were tested in stage ready for prod

**Review by anthonypetersen — APPROVED** [review]
tested and ready for stage

**Review by JoeArmani — APPROVED** [review]
my changes are ready for prod

**Comment by Davinkjohnson** [comment]
Confirming for @bransteitterbr since he's OOO today. His changes were tested and approved in stage. Ready for Prod.

**Comment by jhflorey** [comment]
My changes are ready to prod

**Review by jhflorey — APPROVED** [review]

**Pull request merged**
