### PR TITLE
Dev -> Stage Sync (Jan. Release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- https://github.com/episphere/connect/issues/722 (@ramavavi)
- https://github.com/episphere/connect/issues/852 (@ramavavi)
- https://github.com/episphere/connect/issues/858 (@anthonypetersen)
- https://github.com/episphere/connect/issues/712 (@anthonypetersen)

### CODE REVIEW

**Review by ramavavi — APPROVED** [review]

**Comment by ramavavi** [comment]
My changes look good in Dev and ready for stage.

**Comment by anthonypetersen** [comment]
Mod 1 Soccer Updates look good in dev, waiting on confirmation for the SSN changes

**Comment by sonyekere** [comment]
Ops team has confirmed that SSN looks good in Dev. This is now ready for Stage

**Review by anthonypetersen — APPROVED** [review]

**Comment by anthonypetersen** [comment]
All changes are ready for stage

**Pull request merged**
