### PR TITLE
Dev -> Stage Sync (June 2024)

### PR DESCRIPTION
**Pull request by anthonypetersen**
Issues Addressed
-----
* https://github.com/episphere/connect/issues/885 - @Gbarra9 
* https://github.com/episphere/connect/issues/945 - @JoeArmani 
* https://github.com/episphere/connect/issues/915 - @amber-emmes 
* https://github.com/episphere/connect/issues/948 - @jhflorey

### CODE REVIEW

**Review by JoeArmani — APPROVED** [review]
tested in dev, ready for stage

**Comment by amber-emmes** [comment]
[915](https://github.com/episphere/connect/issues/915) tested and ready for stage.

**Review by amber-emmes — APPROVED** [review]

**Review by Gbarra9 — APPROVED** [review]
My changes are ready for stage

**Review by jhflorey — APPROVED** [review]

**Comment by jhflorey** [comment]
My code changes are tested in dev and ready for stage

**Comment by anthonypetersen** [comment]
ready for stage

**Pull request merged**
