### PR TITLE
Dev -> Stage Sync (September 2024)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- [PROMIS Survey Not Moving to "Completed" Tab in PWA Once Submitted](https://github.com/episphere/connect/issues/1103) (@jhflorey)
- [Updated code to include localDevFirebaseConfig](https://github.com/episphere/connectApp/pull/833), as part of [Hide External API Keys](https://github.com/episphere/connect/issues/1054) (@amber-emmes)
- [BSWH MySamples Update](https://github.com/episphere/connect/issues/1108) (@Gbarra9)
- [Quest Reload](https://github.com/episphere/connect/issues/759) (@anthonypetersen)
- [2024 Connect Experience Survey requirements](https://github.com/episphere/connect/issues/1073) (@bransteitterbr, @amber-emmes)

### CODE REVIEW

**Review by amber-emmes — APPROVED** [review]
All of my changes look good and are ready for stage.

**Review by jhflorey — APPROVED** [review]

**Comment by jhflorey** [comment]
My changes were tested and ready for stage.

**Review by anthonypetersen — APPROVED** [review]
changes ready for stage

**Review by Gbarra9 — APPROVED** [review]
My change was tested in dev and ready for stage

**Comment by amber-emmes** [comment]
Confirming for Brian, who is out, that [1073](https://github.com/episphere/connect/issues/1073) is ready for stage. All of both my and Brian's changes are ready to go out.

**Pull request merged**
