### PR TITLE
Stage -> Prod Sync (Sep. Release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- https://github.com/episphere/connect/issues/698 (@JoeArmani)
- https://github.com/episphere/connect/issues/699 (@JoeArmani)
- https://github.com/episphere/connect/issues/696 (@bransteitterbr)
- https://github.com/episphere/connect/issues/717 (@anthonypetersen)
- https://github.com/episphere/connect/issues/716. Added new location Detroit to My Samples Page HFH (@ramavavi)
- https://github.com/episphere/connect/issues/727 (@ramavavi)
- https://github.com/episphere/connect/issues/702 (@anthonypetersen)

### CODE REVIEW

**Review by anthonypetersen — APPROVED** [review]

**Comment by anthonypetersen** [comment]
My changes have been tested and approved in stage, ready for prod!

**Comment by JoeArmani** [comment]
My changes have been tested and approved in stage, ready for prod.

**Comment by ramavavi** [comment]
My changes have been tested and approved in stage, ready for prod!

**Comment by anthonypetersen** [comment]
late add has been tested, ready for prod

**Comment by bransteitterbr** [comment]
My update is tested and ready for prod

**Pull request merged**
