### PR TITLE
Dev -> Stage Sync (Mar. Release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- https://github.com/episphere/connect/issues/899 (@amber-emmes)
- https://github.com/episphere/connect/issues/916 (@JoeArmani)
- https://github.com/episphere/connect/issues/901#issuecomment-1979385034. Update BioKit_Mouthwash Assembly Concept ID (@Gbarra9)
- https://github.com/episphere/connectApp/pull/732 (@anthonypetersen)
- https://github.com/episphere/connect/issues/907 (@we-ai)
- https://github.com/episphere/connect/issues/925. Added logging to help debug issue (@bransteitterbr)
- https://github.com/episphere/connect/issues/932. Changed text after sending out sign-in email (@we-ai)

### CODE REVIEW

**Review by JoeArmani — APPROVED** [review]
My changes are tested in dev and ready for stage

**Review by amber-emmes — APPROVED** [review]

**Comment by bransteitterbr** [comment]
My changes are ready

**Comment by amber-emmes** [comment]
My changes are ready.

**Comment by Gbarra9** [comment]
My update does not seem to be dependent on the additional email notification testing. I am going to wait till Monday to have the final decision whether the email notification testing is a prerequisite to having my changes being approved and tested.

**Comment by Gbarra9** [comment]
- https://github.com/episphere/connect/issues/901

Tested in dev and decision was made to move to stage. Testing included both pass and failure under certain conditions for client-side emails. Another issue will be made to address the failed testing scenarios.

New issue : https://github.com/episphere/connect/issues/939

**Review by Gbarra9 — APPROVED** [review]

**Pull request merged**
