### PR TITLE
Dev -> Stage Sync (December 2024)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- [yob - birth year in PWA for qx markdown](https://github.com/episphere/connect/issues/1146) (@anthonypetersen)
- [Part 1: User Profile Enhancements for Intro and MyProfile page](https://github.com/episphere/connect/issues/994) (@jhflorey)
- [Update My Samples page content for SFH](https://github.com/episphere/connect/issues/1157) (@Gbarra9)
- [Part 2: User Profile Enhancements for Former Names](https://github.com/episphere/connect/issues/1150) (@jhflorey)
- [Consent+HIPAA HTML: remove the 'I agree' and signature lines](https://github.com/episphere/connect/issues/1144) (@bransteitterbr)
- [PWA Bootstrap 5 upgrade](https://github.com/episphere/connect/issues/1167) and Quest 2 integration (@joeArmani)
- [Part 3: User Profile Enhancements for Contact Information](https://github.com/episphere/connect/issues/1149) (@jhflorey)
- [Cancer Screening History Survey](https://github.com/episphere/connect/issues/1145) (@we-ai)
- [Minor issue: delayed loading of app version](https://github.com/episphere/connect/issues/1171) (@we-ai)
- [handle inactivity timer for multiple tabs and windows](https://github.com/episphere/connectApp/pull/877) (@joeArmani)

### CODE REVIEW

**Review by Gbarra9 — APPROVED** [review]
My changes were tested in dev and ready for stage

**Comment by we-ai** [comment]
My updates were tested in dev and ready for stage.

**Review by bransteitterbr — APPROVED** [review]

**Review by JoeArmani — APPROVED** [review]
My changes are tested in dev and ready for stage.

Note: recently added https://github.com/episphere/connectApp/pull/877 will be tested in dev and stage by tomorrow but will not hold up the Dev-> Stage merge.

**Review by jhflorey — APPROVED** [review]

**Comment by jhflorey** [comment]
My updates were tested in dev and ready for stage.

**Pull request merged**
