### PR TITLE
Stage -> Prod Sync (Aug. Release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- https://github.com/episphere/connectApp/issues/537. Update signature (@jhflorey)
- https://github.com/episphere/connect/issues/688 (@ramavavi)
- https://github.com/episphere/connect/issues/686 (@bransteitterbr)
- https://github.com/episphere/connect/issues/682 (@bransteitterbr)
- https://github.com/episphere/connect/issues/694 (@bransteitterbr)
- https://github.com/episphere/connect/issues/702 (@anthonypetersen)

### CODE REVIEW

**Review by anthonypetersen — APPROVED** [review]

**Comment by anthonypetersen** [comment]
tested and ready for prod

**Comment by jhflorey** [comment]
tested and ready for prod - https://github.com/episphere/connectApp/issues/537#issuecomment-1703103379

**Comment by ramavavi** [comment]
tested and Ready for prod

**Review by bransteitterbr — APPROVED** [review]

**Comment by bransteitterbr** [comment]
Tested and Ready

**Pull request merged**
