### PR TITLE
Dev -> Stage Sync (May 2024 Release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- https://github.com/episphere/connect/issues/992 (@bransteitterbr)
- https://github.com/episphere/connectApp/pull/748 (@bransteitterbr)
- https://github.com/episphere/connect/issues/964 (@anthonypetersen)
- https://github.com/episphere/connect/issues/982 (@jhflorey)
- https://github.com/episphere/connect/issues/942 (@jhflorey)
- https://github.com/episphere/connect/issues/1013 (@JoeArmani)
- https://github.com/episphere/connect/issues/941 (@bransteitterbr)

### CODE REVIEW

**Review by anthonypetersen — APPROVED** [review]
my changes are tested and ready for stage

**Review by bransteitterbr — APPROVED** [review]

**Comment by bransteitterbr** [comment]
Ready for stage

**Comment by jhflorey** [comment]
Ready for Stage

**Review by JoeArmani — APPROVED** [review]
My updates are tested in dev and ready for stage.

**Pull request merged**
