### PR TITLE
Dev -> Stage Sync (Sep. Release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- https://github.com/episphere/connect/issues/698 (@JoeArmani)
- https://github.com/episphere/connect/issues/699 (@JoeArmani)
- https://github.com/episphere/connect/issues/696 (@bransteitterbr)
- https://github.com/episphere/connectApp/pull/642 (@anthonypetersen)
- https://github.com/episphere/connect/issues/716. Added new location Detroit to My Samples Page HFH (@ramavavi)
- https://github.com/episphere/connect/issues/727 (@ramavavi)

### CODE REVIEW

**Comment by anthonypetersen** [comment]
my changes have been tested and confirmed in dev

**Review by anthonypetersen — APPROVED** [review]

**Comment by JoeArmani** [comment]
My changes have been tested and approved in dev.

**Comment by bransteitterbr** [comment]
My changes have been tested and approved in dev

**Comment by ramavavi** [comment]
My changes have been tested and approved in dev.

**Pull request merged**
