### PR TITLE
[#119] Smoother and more transparent transition to eConsent screen

### PR DESCRIPTION
**Pull request by jhflorey**
This PR addresses issue #119 

- Add `The next screens will take you through the informed consent process. They explain more about the study and what it means to take part in Connect. At the end, you can read the full informed consent form and electronic health records release form before you decide if you want to join.` at the bottom of the "how did you hear about the study" question page near the submit/next button.
- Add "Previous" button on the Welcome Stage of the  eConsent screen to  allow the user to return to the `How did you hear about the study` page.
- Keep state of `How did you hear about the study` page while switching between `How did you hear about the study` page and eConsent screen.

### CODE REVIEW

**Comment by anthonypetersen** [comment]
The code itself looks fine though, nice work!

**Review by anthonypetersen — CHANGES_REQUESTED** [review]
See previous comment

**Comment by jhflorey** [comment]
@anthonypetersen i will close this PR and create another PR for dev.Please let me know your thoughts

**Comment by anthonypetersen** [comment]
closing because new PR was made

**Pull request closed without merging**
