### PR TITLE
Update missing container div

### PR DESCRIPTION
**Pull request by bransteitterbr**
If the old html is cached this will attempt to reload the window and get the new div.  If the new div is not loaded it will ignore rendering the selector.  The app will still work it just wont have the ability to change the language from English.

### CODE REVIEW

**Review by Gbarra9 — APPROVED** [review]

**Comment by we-ai** [comment]
Is caching still an issue causing loading of old index.html? @Gbarra9 @bransteitterbr

**Comment by bransteitterbr** [comment]
@we-ai I could not produce the issue locally, but we are seeing enough of the error in Datadog to know that some people are still getting the cached html but the current js.  But after a refresh it seems fine.  That is what this fix is hoping to address.

**Comment by Gbarra9** [comment]
@we-ai I haven't heard anything until now.

**Comment by anthonypetersen** [comment]
code looks pretty similar in both changes, any benefit in putting the reload logic into a shared function?

**Comment by we-ai** [comment]
We may only need to adjust app version number to remove old caches.
And usually people refresh  (or close and reopen)  page when they see things strange, which will trigger a new service worker when a new version is available.

**Comment by we-ai** [comment]
This code may work:
```js
    navigator.serviceWorker.addEventListener("message", (event) => {
        if (event.data.action === "sendAppVersion") {
            const appVersion = event.data.payload;
            document.getElementById("appVersion").textContent = appVersion;
            const savedAppVersion = window.localStorage.getItem("appVersion");
            if (appVersion !== savedAppVersion) {
                window.localStorage.setItem("appVersion", appVersion);
                window.location.reload();
            }
        }
    });
```

**Review by we-ai — APPROVED** [review]

**Review by Gbarra9 — APPROVED** [review]

**Comment by we-ai** [comment]
The new updates look fine to me.

**Pull request merged**
