### PR TITLE
update aria-label screen reader handling for survey buttons

### PR DESCRIPTION
**Pull request by JoeArmani**
Update survey button handling for aria-label property (values read by screen reader).

Format (in en or es):
"Continue" or "Start" +  <Module Name>.

### CODE REVIEW

**Review by anthonypetersen — APPROVED** [review]

**Review by bransteitterbr — APPROVED** [review]

**Comment by JoeArmani** [comment]
I added this PR to the testing list in https://github.com/episphere/connect/issues/1167

**Comment by JoeArmani** [comment]
@cunnaneaq dev tested this passed.

Has this been stage tested yet? If not, could you verify in testing later today?

**Comment by cunnaneaq** [comment]
tested in stage on a MacBook in Firefox - looks good

**Comment by JoeArmani** [comment]
ready for prod

**Comment by JoeArmani** [comment]
in prod

**Pull request merged**
