### PR TITLE
Stage -> Prod Sync (October Release)

### PR DESCRIPTION
**Pull request by anthonypetersen**
Issues Addressed:
* https://github.com/episphere/connect/issues/700 (@anthonypetersen)
* https://github.com/episphere/connect/issues/760 (@anthonypetersen)
* https://github.com/episphere/connect/issues/759 (@anthonypetersen)
* https://github.com/episphere/connect/issues/757 (@ramavavi)
* https://github.com/episphere/connect/issues/737 (@anthonypetersen)

### CODE REVIEW

**Comment by anthonypetersen** [comment]
my changes have been approved and are ready for prod

**Comment by ramavavi** [comment]
My changes have been approved in stage and are ready for prod.

**Review by ramavavi — APPROVED** [review]

**Review by JoeArmani — APPROVED** [review]
Looks good. I did not have any ConnectApp changes this dev cycle.

**Comment by anthonypetersen** [comment]
late updates have been tested - ready for prod

**Pull request merged**
