### PR TITLE
Dev -> Stage Sync (July 2024 Release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- https://github.com/episphere/connect/issues/917 (@anthonypetersen)
- https://github.com/episphere/connect/issues/915 (@bransteitterbr)
- https://github.com/episphere/connect/issues/1048 (@JoeArmani)
- https://github.com/episphere/connect/issues/1017 (@jhflorey)
- https://github.com/episphere/connect/issues/1057 (@jhflorey)
- https://github.com/episphere/connect/issues/1066 (@JoeArmani)
- https://github.com/episphere/connect/issues/1050 (@bransteitterbr)
- https://github.com/episphere/connect/issues/621 (@Gbarra9)

### CODE REVIEW

**Comment by jhflorey** [comment]
My updates are ready for stage.

**Review by jhflorey — APPROVED** [review]

**Review by anthonypetersen — APPROVED** [review]
my change are ready for stage

**Review by JoeArmani — APPROVED** [review]
My changes have been tested in dev. Ready for stage.

**Review by Gbarra9 — APPROVED** [review]
Changes in dev and tested. Ready for stage.

**Review by bransteitterbr — APPROVED** [review]

**Comment by bransteitterbr** [comment]
All Dev tests are done ready for stage

**Pull request merged**
